### PR TITLE
User services implementation

### PR DESCRIPTION
**Pull request by timreimherr**
@wojonet 
Okay, I think this branch is done

### CODE REVIEW

**Comment by timreimherr** [comment]
@wojonet resolved merge conflicts

**Comment by wojonet** [comment]
@timreimherr needs merge conflicts resolved.

**Comment by timreimherr** [comment]
@wojonet okay, fixed merge conflicts

**Comment by wojonet** [comment]
@timreimherr errr, this still has merge conflicts.

**Comment by timreimherr** [comment]
@wojonet okay I'm not joking this time ha. I believe the merge conflicts are fixed!

**Pull request merged**
